# Generated by Django 4.1.4 on 2023-05-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.URLField(),
        ),
    ]
